### ISSUE TITLE
连续开启的第二天，会崩溃，需要手动删除images才会恢复

### ISSUE THREAD

**Issue by 956237586** [newdraw/AppTime#9]
System.IO.IOException
  HResult=0x80070091
  Message=目录不是空的。

  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at AppTime.Recorder.Screenshot(DateTime now, App lastApp)
   at AppTime.Recorder.RecorderThreadProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by newdraw** [comment]
感谢报告😊，代码已经修复。

**Comment by 956237586** [comment]
方便重新打个Release么？

**Comment by 956237586** [comment]
我用最新代码编译后，发现在文件上的弹出的右键菜单会被这个程序弄没
